version: '3.6'

services:
  debmirror-amd64:
    image: ghcr.io/smeetsee/docker-debmirror:main
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    container_name: debmirror-amd64
    volumes:
      - ./
      - /volume1/mirror:/opt/mirror
    restart: 'no'
    entrypoint: [ "bash", "-c", "chmod +x mirrorbuild-amd64.sh && ./mirrorbuild-amd64.sh"]
  debmirror-ports:
    image: ghcr.io/smeetsee/docker-debmirror:main
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    container_name: debmirror-ports
    volumes:
      - ./mirrorbuild-amd64.sh:/opt/mirrorbuild-amd64.sh
      - ./mirrorbuild-ports.sh:/opt/mirrorbuild-ports.sh
      - /volume1/mirror:/opt/mirror
    restart: 'no'
    entrypoint: [ "bash", "-c", "chmod +x mirrorbuild-ports.sh && ./mirrorbuild-ports.sh"]