version: '3.6'

services:
  debmirror-amd64:
    image: ghcr.io/smeetsee/docker-debmirror:latest
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    container_name: debmirror-amd64
    volumes:
      - ./mirrorbuild-amd64.sh:/opt/mirrorbuild-amd64.sh
      - /volume1/mirror:/opt/mirror
    restart: 'no'
    entrypoint: [ "bash", "-c", "chmod +x /opt/mirrorbuild-amd64.sh && /opt/mirrorbuild-amd64.sh"]
  debmirror-ports:
    image: ghcr.io/smeetsee/docker-debmirror:latest
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    container_name: debmirror-ports
    volumes:
      - ./mirrorbuild-ports.sh:/opt/mirrorbuild-ports.sh
      - /volume1/mirror:/opt/mirror
    restart: 'no'
    entrypoint: [ "bash", "-c", "chmod +x /opt/mirrorbuild-ports.sh && /opt/mirrorbuild-ports.sh"]
